### PR TITLE
Plain web-theme: use the full width of the view

### PR DESCRIPTION
**Pull request by jacob-carlborg**
With this change the header and the main content will stretch all the way to the right regardless of the size of the HTML view/window.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
@infininight @sorbits

**Comment by jacob-carlborg** [comment]
Ping @infininight @sorbits.

**Comment by sorbits** [comment]
Doesn’t it already stretch all the way to the right side?

**Comment by jacob-carlborg** [comment]
No, not for me at least. I'm using the option `Show command output: Right of text view`. If the width of the view is wide enough it does not stretch the entire width.

web-theme

**Comment by sorbits** [comment]
I’m unable to reproduce this, could you have local changes?

**Comment by jacob-carlborg** [comment]
I diffed `~/Library/Application Support/TextMate/Managed/Bundles/Themes.tmbundle/Support/web-themes/plain/style.css` and compared what's currently in master, no changes. Are there some other places where there can be local changes affecting this?

BTW, I'm running macOS 10.11.6.

**Comment by jacob-carlborg** [comment]
I found the problem. I have the Markdown Redcarpet bundle installed which seems to contain it's own copy of the web preview theme with a hardcoded value for the width of the `<body>` tag. Disabling that bundle fixes the problem.

**Pull request closed without merging**
